# Generated by Django 5.2.2 on 2026-01-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
